Repository ahmedelazab1220/ecommerce_flower_app, pull requests merged in 2025-04, with the labels that each got.

#9 Feature/FA-7-App-Sections
  lib/core/utils/app_strater.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/routes/routes.dart
  lib/features/cart/presentation/view/cart_screen.dart
  lib/features/categories/presentation/view/categories_screen.dart
  lib/features/home/presentation/view/home_screen.dart
  lib/features/main_layout/presentation/view/main_layout.dart
  lib/features/main_layout/presentation/view_model/cubit/main_layout_cubit.dart
  lib/features/main_layout/presentation/view_model/cubit/main_layout_state.dart
  lib/features/profile/presentation/view/profile_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement

#17 Feature/FA-12-Home-Screen
  android/app/src/main/AndroidManifest.xml
  assets/lotties/loading.json
  assets/translations/ar.json
  assets/translations/en.json
  devtools_options.yaml
  lib/core/assets/app_lotties.dart
  lib/core/utils/app_strater.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/font_responsive/font_responsive.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/location_service/location_service.dart
  lib/core/utils/responsive_util/responsive_util.dart
  lib/core/utils/routes/routes.dart
  lib/core/utils/size_config.dart
  lib/features/home/data/api/home_retrofit_client.dart
  lib/features/home/data/api/home_retrofit_client.g.dart
  lib/features/home/data/data_source/contract/home_local_data_source.dart
  lib/features/home/data/data_source/contract/home_remote_data_source.dart
  lib/features/home/data/data_source/local/home_local_data_source_impl.dart
  lib/features/home/data/data_source/remote/home_remote_data_source_impl.dart
  lib/features/home/data/models/response/best_seller_dto.dart
  lib/features/home/data/models/response/best_seller_dto.g.dart
  lib/features/home/data/models/response/category_dto.dart
  lib/features/home/data/models/response/category_dto.g.dart
  lib/features/home/data/models/response/home_response_dto.dart
  lib/features/home/data/models/response/home_response_dto.g.dart
  lib/features/home/data/models/response/occasion_dto.dart
  lib/features/home/data/models/response/occasion_dto.g.dart
  lib/features/home/data/models/response/product_dto.dart
  lib/features/home/data/models/response/product_dto.g.dart
  lib/features/home/data/repo_impl/home_repo_impl.dart
  lib/features/home/domain/entity/best_seller_entity.dart
  lib/features/home/domain/entity/category_entity.dart
  lib/features/home/domain/entity/home_response_entity.dart
  lib/features/home/domain/entity/occasion_entity.dart
  lib/features/home/domain/entity/product_entity.dart
  lib/features/home/domain/repo/home_repo.dart
  lib/features/home/domain/use_case/get_home_data_use_case.dart
  lib/features/home/presentation/view/home_screen.dart
  lib/features/home/presentation/view/widgets/best_seller_item.dart
  lib/features/home/presentation/view/widgets/best_seller_list_items.dart
  lib/features/home/presentation/view/widgets/category_item.dart
  lib/features/home/presentation/view/widgets/category_list_items.dart
  lib/features/home/presentation/view/widgets/home_app_bar.dart
  lib/features/home/presentation/view/widgets/home_body.dart
  lib/features/home/presentation/view/widgets/home_shared_title_widget.dart
  lib/features/home/presentation/view/widgets/location_container.dart
  lib/features/home/presentation/view/widgets/occasion_item.dart
  lib/features/home/presentation/view/widgets/occasion_list_items.dart
  lib/features/home/presentation/view_model/home_cubit.dart
  lib/features/home/presentation/view_model/home_state.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#18 Fix/FA-12-Home-Screen
  lib/features/home/presentation/view/home_screen.dart
  lib/features/home/presentation/view/widgets/best_seller_item.dart
  lib/features/home/presentation/view/widgets/best_seller_list_items.dart
  lib/features/home/presentation/view/widgets/category_item.dart
  lib/features/home/presentation/view/widgets/category_list_items.dart
  lib/features/home/presentation/view/widgets/location_container.dart
  lib/features/home/presentation/view/widgets/occasion_item.dart
  lib/features/home/presentation/view/widgets/occasion_list_items.dart
  lib/features/home/presentation/view_model/home_cubit.dart
  lib/features/home/presentation/view_model/home_state.dart
Labels: bug, refactor

#19 Fix/FA-13-14-15-16-Github-Actions
  .github/workflows/dart-linting.yml
  .github/workflows/flutter-unit-tests.yml
Labels: bug, devops

#13 Feature/FA-8-Product-Details
  lib/core/utils/di/di.config.dart
  lib/core/utils/routes/routes.dart
  lib/features/auth/data/model/login/login_response_dto.g.dart
  lib/features/auth/data/model/register/register_response_dto/user_dto.g.dart
  lib/features/product_details/presentation/view/screens/product_details_screen.dart
  lib/features/product_details/presentation/view/widgets/bottom_button.dart
  lib/features/product_details/presentation/view/widgets/image_view.dart
  lib/features/product_details/presentation/view/widgets/product_details_body.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement

#24 Fix/FA-1-Register
  lib/core/utils/datasource_excution/dio_module.dart
  lib/features/auth/data/model/register/register_request_dto/register_request_dto.dart
  lib/features/auth/data/model/register/register_response_dto/user_dto.g.dart
  lib/features/auth/data/repo_impl/auth_repo_impl.dart
  lib/features/auth/domain/entity/register_entity/register_request_entity.dart
  lib/features/auth/presentation/view/screens/login_screen.dart
  lib/features/auth/presentation/view/screens/register_screen.dart
  lib/features/auth/presentation/view/widgets/register/register_form.dart
  lib/features/auth/presentation/view/widgets/register/register_radio_buttons.dart
  lib/features/auth/presentation/view/widgets/register/register_text_field_section.dart
  lib/features/auth/presentation/view_model/login/login_cubit.dart
  lib/features/auth/presentation/view_model/register/register_cubit.dart
  lib/features/auth/presentation/view_model/register/register_state.dart
Labels: bug, refactor

#27 Refactor/FA-9-Occasions
  lib/core/utils/di/di.config.dart
  lib/features/categories/presentation/view_model/categories_cubit.dart
  lib/features/home/presentation/view/widgets/occasion_list_items.dart
  lib/features/occasions/data/data_source/contract/occasion_remote_data_source.dart
  lib/features/occasions/data/data_source/occasion_remote_data_source_impl.dart
  lib/features/occasions/data/model/meta_data_dto.dart
  lib/features/occasions/data/model/meta_data_dto.g.dart
  lib/features/occasions/data/model/occasion_dto.dart
  lib/features/occasions/data/model/occasion_dto.g.dart
  lib/features/occasions/data/model/occasions_response_dto.dart
  lib/features/occasions/data/model/occasions_response_dto.g.dart
  lib/features/occasions/data/model/product_dto.dart
  lib/features/occasions/data/model/product_dto.g.dart
  lib/features/occasions/data/model/products_response_dto.dart
  lib/features/occasions/data/model/products_response_dto.g.dart
  lib/features/occasions/data/repo_impl/occasion_repo_impl.dart
  lib/features/occasions/domain/entity/occasion_entity.dart
  lib/features/occasions/domain/entity/occasions_entity.dart
  lib/features/occasions/domain/entity/occasions_response_entity.dart
  lib/features/occasions/domain/repo/occasion_repo.dart
  lib/features/occasions/domain/usecase/get_all_occasions_usecase.dart
  lib/features/occasions/presentation/view/screen/occasion_screen.dart
  lib/features/occasions/presentation/view/widgets/custom_occasion_tab_bar.dart
  lib/features/occasions/presentation/view/widgets/product_item.dart
  lib/features/occasions/presentation/view/widgets/product_view.dart
  lib/features/occasions/presentation/view_model/occasion_cubit.dart
  lib/features/occasions/presentation/view_model/occasion_state.dart
Labels: refactor

#26 Feature/FA-17-Edit-Profile
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/datasource_excution/api_constants.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/core/utils/widgets/default_avatar.dart
  lib/features/auth/presentation/view/widgets/login/remember_me_and_forgot_password.dart
  lib/features/edit_profile/data/api/edit_profile_retrofit_client.dart
  lib/features/edit_profile/data/api/edit_profile_retrofit_client.g.dart
  lib/features/edit_profile/data/data_source/contract/edit_profile_local_data_source.dart
  lib/features/edit_profile/data/data_source/contract/edit_profile_remote_data_source.dart
  lib/features/edit_profile/data/data_source/local/edit_profile_local_data_source_impl.dart
  lib/features/edit_profile/data/data_source/remote/edit_profile_remote_data_source_impl.dart
  lib/features/edit_profile/data/models/edit_profile/request/edit_profile_request_dto.dart
  lib/features/edit_profile/data/models/edit_profile/request/edit_profile_request_dto.g.dart
  lib/features/edit_profile/data/models/edit_profile/response/edit_profile_response_dto.dart
  lib/features/edit_profile/data/models/edit_profile/response/edit_profile_response_dto.g.dart
  lib/features/edit_profile/data/models/user_dto.dart
  lib/features/edit_profile/data/models/user_dto.g.dart
  lib/features/edit_profile/data/repo_impl/edit_profile_repo_impl.dart
  lib/features/edit_profile/domain/entity/edit_profile/edit_profile_request.dart
  lib/features/edit_profile/domain/entity/user_entity.dart
  lib/features/edit_profile/domain/repo/edit_profile_repo.dart
  lib/features/edit_profile/domain/use_case/edit_profile_use_case.dart
  lib/features/edit_profile/domain/use_case/upload_profile_image_use_case.dart
  lib/features/edit_profile/presentation/view/edit_profile_bloc_listener.dart
  lib/features/edit_profile/presentation/view/edit_profile_screen.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_body.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_change_password.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_form.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_gender.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_user_image.dart
  lib/features/edit_profile/presentation/view_model/cubit/edit_profile_cubit.dart
  lib/features/edit_profile/presentation/view_model/cubit/edit_profile_state.dart
  lib/features/profile/presentation/view/profile_screen.dart
  lib/main.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#23 Feature/FA-21-Reset-Password
  lib/core/utils/datasource_excution/dio_module.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/routes/routes.dart
  lib/core/utils/shared_features/add_to_cart/data/model/response/cart_items.dart
  lib/core/utils/shared_features/add_to_cart/data/model/response/cart_items.g.dart
  lib/core/utils/shared_features/add_to_cart/data/model/response/product.dart
  lib/core/utils/shared_features/add_to_cart/data/model/response/product.g.dart
  lib/features/cart/data/model/cart.dart
  lib/features/cart/data/model/cart.g.dart
  lib/features/cart/data/model/cart_items.dart
  lib/features/cart/data/model/cart_items.g.dart
  lib/features/cart/data/model/product.dart
  lib/features/cart/data/model/product.g.dart
  lib/features/change_password/data/api/change_password_retrofit_client.dart
  lib/features/change_password/data/api/change_password_retrofit_client.g.dart
  lib/features/change_password/data/data_source/contract/change_password_remote_data_source.dart
  lib/features/change_password/data/data_source/remote/change_password_data_source_impl.dart
  lib/features/change_password/data/models/change_password_request_dto/change_password_request_dto.dart
  lib/features/change_password/data/models/change_password_request_dto/change_password_request_dto.g.dart
  lib/features/change_password/data/models/change_password_response_dto/change_password_response_dto.dart
  lib/features/change_password/data/models/change_password_response_dto/change_password_response_dto.g.dart
  lib/features/change_password/data/repo_impl/change_password_repo_impl.dart
  lib/features/change_password/domain/entities/change_password_request_entity.dart
  lib/features/change_password/domain/repo/change_password_repo.dart
  lib/features/change_password/domain/use_case/change_password_use_case.dart
  lib/features/change_password/presentation/view/screens/change_password_screen.dart
  lib/features/change_password/presentation/view/widgets/change_password_form.dart
  lib/features/change_password/presentation/view_model/change_password_cubit.dart
  lib/features/change_password/presentation/view_model/change_password_state.dart
  lib/features/occasions/presentation/view/widgets/product_view.dart
  lib/features/product_details/presentation/view_model/product_details_cubit.dart
Labels: enhancement

#22 Feature/FA-18-Profile-Main-Screen
  assets/svgs/Transaction-order.svg
  assets/svgs/back.svg
  assets/svgs/logout.svg
  assets/svgs/notification.svg
  assets/svgs/pen.svg
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/assets/app_icons.dart
  lib/core/utils/app_strater.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/widgets/default_avater.dart
  lib/features/auth/data/model/login/login_response_dto.g.dart
  lib/features/edit_profile/domain/entity/user_entity.dart
  lib/features/edit_profile/presentation/view/edit_profile_screen.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_body.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_form.dart
  lib/features/edit_profile/presentation/view_model/cubit/edit_profile_cubit.dart
  lib/features/main_layout/presentation/view/main_layout.dart
  lib/features/main_layout/presentation/view_model/cubit/main_layout_cubit.dart
  lib/features/occasions/presentation/view/screen/occasion_screen.dart
  lib/features/profile/data/api/profile_retrofit_client.dart
  lib/features/profile/data/api/profile_retrofit_client.g.dart
  lib/features/profile/data/data_source/contract/profile_local_data_source.dart
  lib/features/profile/data/data_source/contract/profile_remote_data_source.dart
  lib/features/profile/data/data_source/local/profile_local_data_source_impl.dart
  lib/features/profile/data/data_source/remote/profile_remote_data_source_impl.dart
  lib/features/profile/data/model/user_data_response_dto.dart
  lib/features/profile/data/model/user_data_response_dto.g.dart
  lib/features/profile/data/model/user_dto.dart
  lib/features/profile/data/model/user_dto.g.dart
  lib/features/profile/data/repo_impl/profile_repo_impl.dart
  lib/features/profile/domain/entity/user_entity.dart
  lib/features/profile/domain/repo/profile_repo.dart
  lib/features/profile/domain/usecase/get_user_data_usecase.dart
  lib/features/profile/domain/usecase/guest_mode_use_case.dart
  lib/features/profile/domain/usecase/logout_use_case.dart
  lib/features/profile/presentation/view/profile_screen.dart
  lib/features/profile/presentation/view/widgets/guest_mode_section.dart
  lib/features/profile/presentation/view/widgets/logout_section.dart
  lib/features/profile/presentation/view/widgets/notification_section.dart
  lib/features/profile/presentation/view/widgets/order_section.dart
  lib/features/profile/presentation/view/widgets/profile_header.dart
  lib/features/profile/presentation/view/widgets/translation_and_about_us_section.dart
  lib/features/profile/presentation/view/widgets/translation_bottom_sheet.dart
  lib/features/profile/presentation/view_model/profile_cubit.dart
  lib/features/profile/presentation/view_model/profile_state.dart
  lib/main.dart
Labels: enhancement

#28 Feature/FA-8-Product-Details
  lib/core/utils/app_strater.dart
  lib/core/utils/constants.dart
  lib/core/utils/datasource_excution/dio_module.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/core/utils/shared_features/add_to_cart/data/data_source/local/add_to_cart_local_data_source_impl.dart
  lib/core/utils/shared_features/add_to_cart/data/model/response/cart_items.g.dart
  lib/core/utils/shared_features/add_to_cart/data/repo_impl/add_to_cart_repo_impl.dart
  lib/core/utils/shared_features/add_to_cart/domain/repo/add_to_cart_repo.dart
  lib/core/utils/shared_features/add_to_cart/domain/usecase/is_guest_use_case.dart
  lib/core/utils/shared_preference_module.dart
  lib/core/utils/widgets/default_avater.dart
  lib/features/auth/data/api/auth_retrofit_client.g.dart
  lib/features/auth/data/model/login/request/login_request_dto.g.dart
  lib/features/categories/data/api/categories_retrofit_client.g.dart
  lib/features/categories/data/models/products_response/product.g.dart
  lib/features/categories/data/models/products_response/products_response.g.dart
  lib/features/edit_profile/data/api/edit_profile_retrofit_client.dart
  lib/features/edit_profile/data/api/edit_profile_retrofit_client.g.dart
  lib/features/edit_profile/data/api/upload_file_api_manager.dart
  lib/features/edit_profile/data/api/upload_file_api_manager_impl.dart
  lib/features/edit_profile/data/data_source/remote/edit_profile_remote_data_source_impl.dart
  lib/features/edit_profile/presentation/view/edit_profile_bloc_listener.dart
  lib/features/edit_profile/presentation/view/widgets/edit_profile_change_password.dart
  lib/features/edit_profile/presentation/view_model/cubit/edit_profile_cubit.dart
  lib/features/edit_profile/presentation/view_model/cubit/edit_profile_state.dart
  lib/features/most_selling_products/presentation/view/screens/best_sellers_screen.dart
  lib/features/product_details/presentation/view/screens/product_details_screen.dart
  lib/features/product_details/presentation/view/widgets/bottom_button.dart
  lib/features/product_details/presentation/view/widgets/image_view.dart
  lib/features/product_details/presentation/view/widgets/product_details_body.dart
  lib/features/product_details/presentation/view_model/product_details_cubit.dart
  lib/features/profile/data/api/profile_retrofit_client.g.dart
  lib/features/profile/data/model/user_data_response_dto.g.dart
  lib/features/profile/presentation/view/widgets/profile_header.dart
  lib/generated/assets.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, refactor

#31 Refactor/FA-21-Reset-Password
  lib/core/functions/initial_route_function.dart
  lib/features/change_password/presentation/view/screens/change_password_screen.dart
  lib/features/change_password/presentation/view/widgets/change_password_form.dart
  lib/features/change_password/presentation/view_model/change_password_cubit.dart
  lib/features/change_password/presentation/view_model/change_password_state.dart
  test/core/functions/inital_route_function_test.dart
  test/core/functions/inital_route_function_test.mocks.dart
  test/widget_test.dart
Labels: refactor

#33 Feature/FA-7-App-Sections
  lib/core/utils/bottom_nav_bar_visibility/scroll_visibility_controller.dart
  lib/features/categories/presentation/view/screens/categories_screen.dart
  lib/features/categories/presentation/view/widgets/products_grid.dart
  lib/features/categories/presentation/view_model/categories_cubit.dart
  lib/features/home/presentation/view/home_screen.dart
  lib/features/home/presentation/view/widgets/home_body.dart
  lib/features/home/presentation/view_model/home_cubit.dart
  lib/features/main_layout/presentation/view/main_layout.dart
  lib/features/main_layout/presentation/view_model/cubit/main_layout_cubit.dart
  lib/features/profile/presentation/view/profile_screen.dart
  lib/features/profile/presentation/view_model/profile_cubit.dart
Labels: enhancement

#34 Feature/FA-24-Filter
  assets/svgs/filter.svg
  lib/core/assets/app_icons.dart
  lib/features/categories/data/api/categories_retrofit_client.dart
  lib/features/categories/data/api/categories_retrofit_client.g.dart
  lib/features/categories/data/data_source/contract/categories_remote_data_source.dart
  lib/features/categories/data/data_source/remote/categories_remote_data_source_impl.dart
  lib/features/categories/data/repo_impl/categories_repo_impl.dart
  lib/features/categories/domain/repo/categories_repo.dart
  lib/features/categories/domain/use_cases/get_products_use_case.dart
  lib/features/categories/presentation/view/widgets/bottom_sheet_filteration.dart
  lib/features/categories/presentation/view/widgets/products_grid.dart
  lib/features/categories/presentation/view/widgets/search_filter_bar.dart
  lib/features/categories/presentation/view_model/categories_cubit.dart
  lib/features/categories/presentation/view_model/categories_state.dart
Labels: enhancement

#37 Feature/FA-28-Terms-And-Conditions
  assets/terms_and_about/terms_and_conditions_json_file_en_ar.json
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/constants.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/features/categories/presentation/view_model/categories_cubit.dart
  lib/features/profile/presentation/view/widgets/translation_and_about_us_section.dart
  lib/features/terms_and_conditions/domain/entity/term_section.dart
  lib/features/terms_and_conditions/domain/entity/term_section_localized_string.dart
  lib/features/terms_and_conditions/domain/entity/term_section_style.dart
  lib/features/terms_and_conditions/domain/entity/term_section_text_align_style.dart
  lib/features/terms_and_conditions/presentation/view/terms_and_conditions_screen.dart
  lib/features/terms_and_conditions/presentation/view/widgets/handle_terms_empty_state.dart
  lib/features/terms_and_conditions/presentation/view/widgets/handle_terms_loading_state.dart
  lib/features/terms_and_conditions/presentation/view/widgets/term_content_widget.dart
  lib/features/terms_and_conditions/presentation/view/widgets/term_section_widget.dart
  lib/features/terms_and_conditions/presentation/view/widgets/terms_and_conditions_body.dart
  lib/features/terms_and_conditions/utils/load_terms.dart
  lib/features/terms_and_conditions/utils/term_style_parser.dart
  pubspec.yaml
Labels: enhancement

#41 Feature/FA-27-User-Addresses
  assets/svgs/edit.svg
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/features/saved_addresses/data/api/saved_addresses_retrofit_client.dart
  lib/features/saved_addresses/data/api/saved_addresses_retrofit_client.g.dart
  lib/features/saved_addresses/data/data_source/contract/saved_addresses_remote_data_source.dart
  lib/features/saved_addresses/data/data_source/remote/saved_addresses_remote_data_source_impl.dart
  lib/features/saved_addresses/data/models/address_dto.dart
  lib/features/saved_addresses/data/models/address_dto.g.dart
  lib/features/saved_addresses/data/models/delete_addresses/delete_addresses_response_dto.dart
  lib/features/saved_addresses/data/models/delete_addresses/delete_addresses_response_dto.g.dart
  lib/features/saved_addresses/data/models/saved_addresses/saved_addresses_response_dto.dart
  lib/features/saved_addresses/data/models/saved_addresses/saved_addresses_response_dto.g.dart
  lib/features/saved_addresses/data/repo_impl/saved_addresses_repo_impl.dart
  lib/features/saved_addresses/domain/entity/address_entity.dart
  lib/features/saved_addresses/domain/repo/saved_addresses_repo.dart
  lib/features/saved_addresses/domain/use_case/delete_user_address_use_case.dart
  lib/features/saved_addresses/domain/use_case/get_user_saved_addresses_use_case.dart
  lib/features/saved_addresses/presentation/view/saved_address_screen.dart
  lib/features/saved_addresses/presentation/view/widgets/handle_empty_address_state.dart
  lib/features/saved_addresses/presentation/view/widgets/handle_loading_address_state.dart
  lib/features/saved_addresses/presentation/view/widgets/saved_address_body.dart
  lib/features/saved_addresses/presentation/view/widgets/saved_address_item.dart
  lib/features/saved_addresses/presentation/view/widgets/saved_address_list_item.dart
  lib/features/saved_addresses/presentation/view_model/cubit/saved_address_cubit.dart
  lib/features/saved_addresses/presentation/view_model/cubit/saved_address_state.dart
Labels: enhancement

#42 Feature/FA-8-Product-Details
  assets/lotties/check.json
  assets/lotties/error.json
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/assets/app_lotties.dart
  lib/core/utils/dialogs/app_dialogs.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/features/product_details/presentation/view/screens/product_details_screen.dart
  lib/features/product_details/presentation/view/widgets/bottom_button.dart
  lib/features/product_details/presentation/view_model/product_details_state.dart
  lib/generated/assets.dart
Labels: enhancement

#44 Fix/FA-30-Checkout-Page
  lib/core/utils/datasource_excution/api_constants.dart
  lib/features/checkout/domain/repo/checkout_repo.dart
  lib/features/checkout/presentation/view/screen/checkout_screen.dart
  lib/features/checkout/presentation/view/widgets/add_new_address_button.dart
  lib/features/checkout/presentation/view/widgets/add_new_btn.dart
  lib/features/checkout/presentation/view/widgets/address_item.dart
  lib/features/checkout/presentation/view/widgets/delivery_addresses_section.dart
  lib/features/checkout/presentation/view/widgets/delivery_time_section.dart
  lib/features/checkout/presentation/view/widgets/is_gift_form.dart
  lib/features/checkout/presentation/view/widgets/is_gift_section.dart
  lib/features/checkout/presentation/view/widgets/payment_item.dart
  lib/features/checkout/presentation/view/widgets/payment_section.dart
  lib/features/checkout/presentation/view/widgets/payment_web_view_screen.dart
  lib/features/checkout/presentation/view/widgets/prices_section.dart
  lib/features/checkout/presentation/view/widgets/ripple_animation.dart
  lib/features/checkout/presentation/view/widgets/total_price_section.dart
  lib/features/checkout/presentation/view/widgets/track_order_success_screen.dart
  lib/features/checkout/presentation/view_model/checkout_cubit.dart
  lib/generated/assets.dart
  lib/main.dart
Labels: wontfix, refactor, chore

#46 Feature/FA-26-Address-Details
  assets/addresses/cities.json
  assets/addresses/states.json
  assets/svgs/edit.svg
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/constants.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/core/utils/validator/validator.dart
  lib/features/address_details/data/api/address_details_retrofit_client.dart
  lib/features/address_details/data/api/address_details_retrofit_client.g.dart
  lib/features/address_details/data/data_sources/contract/address_details_local_data_source.dart
  lib/features/address_details/data/data_sources/contract/address_details_remote_data_source.dart
  lib/features/address_details/data/data_sources/local/address_details_local_data_source_impl.dart
  lib/features/address_details/data/data_sources/remote/address_details_remote_data_source_impl.dart
  lib/features/address_details/data/models/request/address_details_request_dto.dart
  lib/features/address_details/data/models/request/address_details_request_dto.g.dart
  lib/features/address_details/data/models/response/address_details_response_dto.dart
  lib/features/address_details/data/models/response/address_details_response_dto.g.dart
  lib/features/address_details/data/models/response/address_dto.dart
  lib/features/address_details/data/models/response/address_dto.g.dart
  lib/features/address_details/data/models/response/city_dto.dart
  lib/features/address_details/data/models/response/city_dto.g.dart
  lib/features/address_details/data/models/response/state_dto.dart
  lib/features/address_details/data/models/response/state_dto.g.dart
  lib/features/address_details/data/repo_impl/address_details_repo_impl.dart
  lib/features/address_details/domain/entities/address_details_request_entity.dart
  lib/features/address_details/domain/entities/city_entity.dart
  lib/features/address_details/domain/entities/state_entity.dart
  lib/features/address_details/domain/repo/address_details_repo.dart
  lib/features/address_details/domain/use_cases/add_adderss_use_case.dart
  lib/features/address_details/domain/use_cases/get_cities_use_case.dart
  lib/features/address_details/domain/use_cases/get_states_use_case.dart
  lib/features/address_details/domain/use_cases/update_address_use_case.dart
  lib/features/address_details/presentation/view/screens/address_details_screen.dart
  lib/features/address_details/presentation/view/widgets/address_details_body.dart
  lib/features/address_details/presentation/view/widgets/address_details_form.dart
  lib/features/address_details/presentation/view/widgets/dropdown_buttons.dart
  lib/features/address_details/presentation/view/widgets/location_map_view.dart
  lib/features/address_details/presentation/view_model/address_details_cubit.dart
  lib/features/address_details/presentation/view_model/address_details_state.dart
  lib/features/checkout/presentation/view/widgets/add_new_address_button.dart
  lib/features/product_details/presentation/view/widgets/bottom_button.dart
  lib/features/saved_addresses/presentation/view/widgets/saved_address_item.dart
  lib/main.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#47 Fix/FA-30-Checkout-Page
  lib/core/utils/routes/routes.dart
  lib/core/utils/shared_models/address_entity.dart
  lib/features/checkout/data/api/checkout_retrofit_client.dart
  lib/features/checkout/data/model/request/add_order_request_dto.dart
  lib/features/checkout/data/model/request/shipping_address.dart
  lib/features/checkout/data/model/response/addresses/addresses.dart
  lib/features/checkout/data/repo_impl/checkout_repo_impl.dart
  lib/features/checkout/domain/entity/add_order_request_entity.dart
  lib/features/checkout/domain/repo/checkout_repo.dart
  lib/features/checkout/domain/usecase/add_cache_order_use_case.dart
  lib/features/checkout/domain/usecase/add_credit_order_use_case.dart
  lib/features/checkout/domain/usecase/get_addresses_use_case.dart
  lib/features/checkout/presentation/view/widgets/delivery_addresses_section.dart
  lib/features/checkout/presentation/view/widgets/delivery_time_section.dart
  lib/features/checkout/presentation/view/widgets/total_price_section.dart
  lib/features/checkout/presentation/view/widgets/track_order_success_screen.dart
  lib/features/checkout/presentation/view_model/checkout_cubit.dart
  lib/features/checkout/presentation/view_model/checkout_state.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: enhancement, refactor, chore

#49 Refactor/FA-27-User-Addresses
  lib/core/utils/routes/routes.dart
  lib/features/address_details/presentation/view/screens/address_details_screen.dart
  lib/features/address_details/presentation/view_model/address_details_cubit.dart
  lib/features/address_details/presentation/view_model/address_details_state.dart
  lib/features/saved_addresses/data/models/address_dto.dart
  lib/features/saved_addresses/data/repo_impl/saved_addresses_repo_impl.dart
  lib/features/saved_addresses/domain/entity/address_entity.dart
  lib/features/saved_addresses/domain/repo/saved_addresses_repo.dart
  lib/features/saved_addresses/domain/use_case/delete_user_address_use_case.dart
  lib/features/saved_addresses/domain/use_case/get_user_saved_addresses_use_case.dart
  lib/features/saved_addresses/presentation/view/widgets/saved_address_item.dart
  lib/features/saved_addresses/presentation/view/widgets/saved_address_list_item.dart
  lib/features/saved_addresses/presentation/view_model/cubit/saved_address_cubit.dart
Labels: refactor, chore

#51 Feature/FA-33-Firebase-App-Distribution
  android/app/build.gradle.kts
  android/app/google-services.json
  android/settings.gradle.kts
  firebase.json
  lib/core/utils/app_strater.dart
  lib/firebase_options.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: devops

#55 Feature/FA-31-Integrate-Firebase-Crashlytics
  firebase.json
  lib/core/utils/app_strater.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#56 Feature/FA-32-Github-Actions-Firebase-App-Distribution
  .github/workflows/flutter_firebase_app_distribution.yaml
Labels: devops

#50 Feature/FA-35-Notifications-List
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/datasource_excution/api_constants.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/features/notifications/data/api/notification_retrofit_client.dart
  lib/features/notifications/data/api/notification_retrofit_client.g.dart
  lib/features/notifications/data/data_source/contract/notification_local_data_source.dart
  lib/features/notifications/data/data_source/contract/notification_remote_data_source.dart
  lib/features/notifications/data/data_source/local/notification_local_data_source_impl.dart
  lib/features/notifications/data/data_source/remote/notification_remote_data_source_impl.dart
  lib/features/notifications/data/model/delete_notification_by_id_response_dto.dart
  lib/features/notifications/data/model/delete_notification_by_id_response_dto.g.dart
  lib/features/notifications/data/model/get_all_notification_response_dto.dart
  lib/features/notifications/data/model/get_all_notification_response_dto.g.dart
  lib/features/notifications/data/model/get_notification_by_id_response_dto.dart
  lib/features/notifications/data/model/get_notification_by_id_response_dto.g.dart
  lib/features/notifications/data/model/metadata.dart
  lib/features/notifications/data/model/metadata.g.dart
  lib/features/notifications/data/model/notifications.dart
  lib/features/notifications/data/model/notifications.g.dart
  lib/features/notifications/data/repo_impl/notification_repo_impl.dart
  lib/features/notifications/domain/entity/notifications_entity.dart
  lib/features/notifications/domain/repo/notification_repo.dart
  lib/features/notifications/domain/usecase/delete_notification_by_id_use_case.dart
  lib/features/notifications/domain/usecase/get_all_notifications_use_case.dart
  lib/features/notifications/domain/usecase/get_notification_by_id_use_case.dart
  lib/features/notifications/presentation/view/screen/notification_details.dart
  lib/features/notifications/presentation/view/screen/notification_screen.dart
  lib/features/notifications/presentation/view/widgets/delete_confirmation_dialog.dart
  lib/features/notifications/presentation/view/widgets/notification_app_bar.dart
  lib/features/notifications/presentation/view/widgets/notification_item.dart
  lib/features/notifications/presentation/view/widgets/notification_list.dart
  lib/features/notifications/presentation/view/widgets/notification_slidable_item.dart
  lib/features/notifications/presentation/view_model/notification_cubit.dart
  lib/features/notifications/presentation/view_model/notification_state.dart
  lib/features/profile/presentation/view/profile_screen.dart
  lib/generated/assets.dart
  linux/runner/my_application.cc
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#58 Feature/FA-35-Notifications-List
  assets/lotties/empty_notification.json
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/assets/app_lotties.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/features/notifications/data/api/notification_retrofit_client.dart
  lib/features/notifications/data/data_source/contract/notification_local_data_source.dart
  lib/features/notifications/data/data_source/contract/notification_remote_data_source.dart
  lib/features/notifications/data/data_source/local/notification_local_data_source_impl.dart
  lib/features/notifications/data/data_source/remote/notification_remote_data_source_impl.dart
  lib/features/notifications/data/model/delete_notification_by_id_response_dto.dart
  lib/features/notifications/data/model/delete_notification_by_id_response_dto.g.dart
  lib/features/notifications/data/model/get_all_notification_response_dto.dart
  lib/features/notifications/data/model/get_all_notification_response_dto.g.dart
  lib/features/notifications/data/model/get_notification_by_id_response_dto.dart
  lib/features/notifications/data/model/get_notification_by_id_response_dto.g.dart
  lib/features/notifications/data/model/metadata_dto.dart
  lib/features/notifications/data/model/metadata_dto.g.dart
  lib/features/notifications/data/model/notification_dto.dart
  lib/features/notifications/data/model/notification_dto.g.dart
  lib/features/notifications/data/repo_impl/notification_repo_impl.dart
  lib/features/notifications/domain/entity/notification_entity.dart
  lib/features/notifications/domain/repo/notification_repo.dart
  lib/features/notifications/domain/usecase/get_all_notifications_use_case.dart
  lib/features/notifications/domain/usecase/get_notification_by_id_use_case.dart
  lib/features/notifications/presentation/view/screen/notification_details.dart
  lib/features/notifications/presentation/view/screen/notification_screen.dart
  lib/features/notifications/presentation/view/widgets/delete_confirmation_dialog.dart
  lib/features/notifications/presentation/view/widgets/notification_app_bar.dart
  lib/features/notifications/presentation/view/widgets/notification_item.dart
  lib/features/notifications/presentation/view/widgets/notification_list.dart
  lib/features/notifications/presentation/view/widgets/notification_slidable_item.dart
  lib/features/notifications/presentation/view_model/notification_cubit.dart
  lib/features/notifications/presentation/view_model/notification_state.dart
Labels: enhancement, refactor, chore

#59 Test/FA-12-Home-Screen
  test/constants_factory.dart
  test/features/home/data/data_source/remote/home_remote_data_source_impl_test.dart
  test/features/home/data/data_source/remote/home_remote_data_source_impl_test.mocks.dart
  test/features/home/data/models/home_model_factory.dart
  test/features/home/data/repo_impl/home_repo_impl_test.dart
  test/features/home/data/repo_impl/home_repo_impl_test.mocks.dart
Labels: ready for testing

#53 Feature/FA-36-Orders-Page
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/features/orders/data/api/orders_retrofit_client.dart
  lib/features/orders/data/api/orders_retrofit_client.g.dart
  lib/features/orders/data/data_source/contract/orders_remote_datasource.dart
  lib/features/orders/data/data_source/remote/orders_remote_datasource_impl.dart
  lib/features/orders/data/model/metadata_dto.dart
  lib/features/orders/data/model/metadata_dto.g.dart
  lib/features/orders/data/model/order_items_dto.dart
  lib/features/orders/data/model/order_items_dto.g.dart
  lib/features/orders/data/model/order_response_dto.dart
  lib/features/orders/data/model/order_response_dto.g.dart
  lib/features/orders/data/model/orders_dto.dart
  lib/features/orders/data/model/orders_dto.g.dart
  lib/features/orders/data/model/product_dto.dart
  lib/features/orders/data/model/product_dto.g.dart
  lib/features/orders/data/repo_impl/orders_repo_impl.dart
  lib/features/orders/domain/entity/order_entity.dart
  lib/features/orders/domain/entity/order_item_entity.dart
  lib/features/orders/domain/repo/orders_repo.dart
  lib/features/orders/domain/usecase/get_orders_usecase.dart
  lib/features/orders/presentation/view/screens/orders_screen.dart
  lib/features/orders/presentation/view/widgets/custom_orders_tab_bar.dart
  lib/features/orders/presentation/view/widgets/order_item.dart
  lib/features/orders/presentation/view/widgets/orders_body.dart
  lib/features/orders/presentation/view/widgets/orders_error_view.dart
  lib/features/orders/presentation/view/widgets/orders_loading_view.dart
  lib/features/orders/presentation/view_model/orders_cubit.dart
  lib/features/orders/presentation/view_model/orders_state.dart
  lib/features/profile/presentation/view/widgets/order_section.dart
Labels: enhancement

#45 Feature/FA-25-Search
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/utils/constants.dart
  lib/core/utils/di/di.config.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/routes/routes.dart
  lib/features/search/data/api/search_retrofit_client.dart
  lib/features/search/data/api/search_retrofit_client.g.dart
  lib/features/search/data/data_source/contract/search_remote_data_source.dart
  lib/features/search/data/data_source/remote/search_remote_data_source_impl.dart
  lib/features/search/data/model/metadata_dto.dart
  lib/features/search/data/model/metadata_dto.g.dart
  lib/features/search/data/model/products_dto.dart
  lib/features/search/data/model/products_dto.g.dart
  lib/features/search/data/model/search_response_dto.dart
  lib/features/search/data/model/search_response_dto.g.dart
  lib/features/search/data/repo_impl/search_repo_impl.dart
  lib/features/search/domain/repo/search_repo.dart
  lib/features/search/domain/usecase/search_usecase.dart
  lib/features/search/presentation/view/screens/search_screen.dart
  lib/features/search/presentation/view/widgets/search_body.dart
  lib/features/search/presentation/view/widgets/search_field.dart
  lib/features/search/presentation/view_model/search_cubit.dart
  lib/features/search/presentation/view_model/search_state.dart
  pubspec.lock
Labels: enhancement
